CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;

CREATE TABLE "WinEvents" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EventId" integer NOT NULL,
    "LogName" text NOT NULL,
    "MachineName" text NOT NULL,
    "Level" text NOT NULL,
    "TimeCreated" timestamp with time zone NOT NULL,
    "EventData" jsonb,
    CONSTRAINT "PK_WinEvents" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260204045917_InitialCreate', '8.0.0');

COMMIT;

START TRANSACTION;

ALTER TABLE "WinEvents" ALTER COLUMN "Level" DROP NOT NULL;

CREATE INDEX "IX_WinEvents_EventId" ON "WinEvents" ("EventId");

CREATE INDEX "IX_WinEvents_LogName_TimeCreated" ON "WinEvents" ("LogName", "TimeCreated" DESC);

CREATE INDEX "IX_WinEvents_TimeCreated" ON "WinEvents" ("TimeCreated" DESC);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260219223345_AddIndexes', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE "Heartbeats" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MachineName" text NOT NULL,
    "IsAlive" boolean NOT NULL,
    "LastSeen" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_Heartbeats" PRIMARY KEY ("Id")
);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260220152754_AddHeartbeatTable', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE "WinNetworkConnections" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "MachineName" text NOT NULL,
    "ProcessName" text,
    "ProcessId" integer,
    "BatchId" uuid NOT NULL,
    "Protocol" text,
    "LocalAddress" text,
    "LocalPort" integer,
    "RemoteAddress" text,
    "RemotePort" integer,
    "State" text,
    "ModuleName" text,
    "SentPackets" bigint NOT NULL,
    "RecvPackets" bigint NOT NULL,
    "SentBytes" bigint NOT NULL,
    "RecvBytes" bigint NOT NULL,
    "TimeCreated" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_WinNetworkConnections" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_WinNetworkConnections_BatchId" ON "WinNetworkConnections" ("BatchId");

CREATE INDEX "IX_WinNetworkConnections_MachineName_TimeCreated" ON "WinNetworkConnections" ("MachineName", "TimeCreated" DESC);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260222230348_AddNetworkConnectionsTable', '8.0.0');

COMMIT;

START TRANSACTION;

CREATE TABLE "AutorunViews" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Time" timestamp with time zone NOT NULL,
    "EntryLocation" text NOT NULL,
    "Entry" text NOT NULL,
    "Enabled" text NOT NULL,
    "Category" text NOT NULL,
    "Profile" text NOT NULL,
    "Description" text NOT NULL,
    "Company" text NOT NULL,
    "ImagePath" text NOT NULL,
    "Version" text NOT NULL,
    "LaunchString" text NOT NULL,
    "Md5" text NOT NULL,
    "Sha1" text NOT NULL,
    "PeSha1" text NOT NULL,
    "PeSha256" text NOT NULL,
    "Sha256" text NOT NULL,
    "Imp" text NOT NULL,
    "BatchId" uuid NOT NULL,
    "MachineName" text NOT NULL,
    "TimeSynced" timestamp with time zone NOT NULL,
    CONSTRAINT "PK_AutorunViews" PRIMARY KEY ("Id")
);

CREATE INDEX "IX_AutorunViews_BatchId" ON "AutorunViews" ("BatchId");

CREATE INDEX "IX_AutorunViews_Entry" ON "AutorunViews" ("Entry");

CREATE INDEX "IX_AutorunViews_MachineName_TimeSynced" ON "AutorunViews" ("MachineName", "TimeSynced" DESC);

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260224194156_AddWinAutorunsTable', '8.0.0');

COMMIT;

