import type { ColumnDef } from '../../../shared/listUtils';
import type { AutorunEntry } from '../shared/types';

export const COLUMNS: ColumnDef<AutorunEntry>[] = [
  {
    key: 'severity',
    label: 'Risk',
    defaultVisible: true,
    sortable: true,
    flex: 0.7,
    minWidth: 60,
    getValue: (e) => e.id,
    searchKeys: ['risk'],
  },
  {
    key: 'machine',
    label: 'Machine',
    defaultVisible: true,
    sortable: true,
    flex: 1.5,
    minWidth: 110,
    getValue: (e) => e.machineName,
    searchKeys: ['host'],
  },
  {
    key: 'entry',
    label: 'Entry',
    defaultVisible: true,
    sortable: true,
    flex: 2.5,
    minWidth: 150,
    getValue: (e) => e.entry,
    searchKeys: ['name'],
  },
  {
    key: 'location',
    label: 'Location',
    defaultVisible: true,
    sortable: true,
    flex: 2.5,
    minWidth: 150,
    getValue: (e) => e.entryLocation,
    searchKeys: ['path', 'reg'],
  },
  {
    key: 'category',
    label: 'Category',
    defaultVisible: true,
    sortable: true,
    flex: 1.2,
    minWidth: 100,
    getValue: (e) => e.category,
  },
  {
    key: 'company',
    label: 'Company',
    defaultVisible: true,
    sortable: true,
    flex: 1.5,
    minWidth: 100,
    getValue: (e) => e.company ?? '',
  },
  {
    key: 'verified',
    label: 'Verified',
    defaultVisible: true,
    sortable: true,
    flex: 1,
    minWidth: 80,
    getValue: (e) => e.verified ?? '',
  },
  {
    key: 'time',
    label: 'Synced',
    defaultVisible: true,
    sortable: true,
    flex: 1,
    minWidth: 90,
    getValue: (e) => e.timeSynced,
  },
];

export function autorunsJsonMapper(e: AutorunEntry): Record<string, unknown> {
  return {
    id: e.id,
    machineName: e.machineName,
    entry: e.entry,
    entryLocation: e.entryLocation,
    category: e.category,
    company: e.company,
    verified: e.verified,
    imagePath: e.imagePath,
    launchString: e.launchString,
    description: e.description,
    sha256: e.sha256,
    md5: e.md5,
    timeSynced: e.timeSynced,
  };
}
