import type { ColumnDef } from '../../../shared/listUtils';
import type { NetworkConnection } from '../shared/types';

export const COLUMNS: ColumnDef<NetworkConnection>[] = [
  {
    key: 'severity',
    label: 'Risk',
    defaultVisible: true,
    sortable: true,
    flex: 0.7,
    minWidth: 60,
    getValue: (c) => c.id,
    searchKeys: ['risk'],
  },
  {
    key: 'machine',
    label: 'Machine',
    defaultVisible: true,
    sortable: true,
    flex: 1.5,
    minWidth: 110,
    getValue: (c) => c.machineName,
    searchKeys: ['host'],
  },
  {
    key: 'process',
    label: 'Process',
    defaultVisible: true,
    sortable: true,
    flex: 2,
    minWidth: 130,
    getValue: (c) => c.processName ?? '',
    searchKeys: ['name', 'module'],
  },
  {
    key: 'protocol',
    label: 'Protocol',
    defaultVisible: true,
    sortable: true,
    flex: 0.8,
    minWidth: 70,
    getValue: (c) => c.protocol ?? '',
  },
  {
    key: 'local',
    label: 'Local',
    defaultVisible: true,
    sortable: true,
    flex: 2,
    minWidth: 140,
    getValue: (c) => `${c.localAddress ?? '*'}:${c.localPort ?? '*'}`,
    searchKeys: ['localAddress', 'localPort'],
  },
  {
    key: 'remote',
    label: 'Remote',
    defaultVisible: true,
    sortable: true,
    flex: 2,
    minWidth: 140,
    getValue: (c) => `${c.remoteAddress ?? '*'}:${c.remotePort ?? '*'}`,
    searchKeys: ['remoteAddress', 'remotePort', 'ip', 'destination'],
  },
  {
    key: 'state',
    label: 'State',
    defaultVisible: true,
    sortable: true,
    flex: 1,
    minWidth: 90,
    getValue: (c) => c.state ?? '',
  },
  {
    key: 'sent',
    label: 'Sent',
    defaultVisible: true,
    sortable: true,
    flex: 0.8,
    minWidth: 70,
    getValue: (c) => c.sentBytes,
  },
  {
    key: 'recv',
    label: 'Recv',
    defaultVisible: true,
    sortable: true,
    flex: 0.8,
    minWidth: 70,
    getValue: (c) => c.recvBytes,
  },
  {
    key: 'time',
    label: 'Time',
    defaultVisible: true,
    sortable: true,
    flex: 1,
    minWidth: 90,
    getValue: (c) => c.timeCreated,
  },
];

export function networkJsonMapper(c: NetworkConnection): Record<string, unknown> {
  return {
    id: c.id,
    machineName: c.machineName,
    processName: c.processName,
    processId: c.processId,
    protocol: c.protocol,
    localAddress: c.localAddress,
    localPort: c.localPort,
    remoteAddress: c.remoteAddress,
    remotePort: c.remotePort,
    state: c.state,
    sentBytes: c.sentBytes,
    recvBytes: c.recvBytes,
    moduleName: c.moduleName,
    timeCreated: c.timeCreated,
  };
}
