[debian]
grafana
teleport
gitea

[rhel]
wordpress-1

[linux:children]
debian
rhel

# --- Variables ---
[linux:vars]
ansible_connection=ssh
; ansible_become_pass=xxx
ansible_become_method=sudo
ansible_become=yes
