[windows]
wkst1 ansible_host=192.168.1.52
ca ansible_host=192.168.1.51
ad ansible_host=192.168.0.203

[windows:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5986
ansible_winrm_server_cert_validation=ignore
ansible_user=ccdcTest\Administrator
ansible_password=1qazxsW@1

[linux]
logontracer ansible_host=192.168.0.123

[linux:vars]
ansible_user=blueteam
ansible_password=1qazxsW@1
ansible_become=true
ansible_become_method=sudo
ansible_become_password=1qazxsW@1
ansible_python_interpreter=/usr/bin/python3.12