[windows]
wkst1 ansible_host=192.168.1.52
ca ansible_host=192.168.1.51
ad ansible_host=192.168.0.203

[windows:vars]
ansible_user=<DOMAIN>\<USER>
ansible_password=<PASSWORD>

[linux]
logontracer ansible_host=192.168.0.123

[linux:vars]
ansible_user=<USER>
ansible_password=<PASSWORD>
ansible_become_password=<PASSWORD>
