[windows]
wkst1 ansible_host=192.168.1.52
ca ansible_host=192.168.1.51
ad ansible_host=192.168.1.50

[windows:vars]
ansible_connection=winrm
ansible_winrm_transport=ntlm
ansible_port=5986
ansible_winrm_server_cert_validation=ignore
ansible_user=Administrator
ansible_password=<enter password here>

[linux]
logontracer ansible_host=192.168.1.187

[linux:vars]
ansible_user=blueteam
ansible_password=<enter password here>
ansible_become=true
ansible_become_method=sudo
ansible_become_password=<enter password here>
ansible_python_interpreter=/usr/bin/python3.12
